### ISSUE TITLE
3D MAE seems to need an input bands with integer multiple of b_patch_size?

### ISSUE THREAD

**Issue by D-Walter** [Ryan21wy/HSIMAE#2]
Thank you for your great work. I still have some confused about the 3D patch embedding process (PatchEmbed).
```assert bands % b_patch_size == 0``` indicates an input bands with integer multiple of b_patch_size is needed.
I'm not sure how to handle the remainder, just discarding? Remapping? Or padding?
Besides, would you consider publish an pre-print version of your manuscript so that I can cite in subsequent work?
Thanks

**Comment by Ryan21wy** [comment]
The group-wise PCA (a PCA variant) is used here to transform raw spectra into fixed length features, i.e. 4 * b_patch_size, as you call remapping. 
This work has been received by JSTARS. you can see it in https://ieeexplore.ieee.org/document/10607879.

**Comment by D-Walter** [comment]
> The group-wise PCA (a PCA variant) is used here to transform raw spectra into fixed length features, i.e. 4 * b_patch_size, as you call remapping. This work has been received by JSTARS. you can see it in https://ieeexplore.ieee.org/document/10607879.

Thanks.
